version: '3'
services:
  elasticsearch01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      node.name: elasticsearch01
      discovery.seed_hosts: elasticsearch02
      cluster.initial_master_nodes: elasticsearch01, elasticsearch02
      ES_JAVA_OPTS: "-Xms16g -Xmx16g"
    volumes:
      - ${PWD}/docker/elasticsearch:/usr/share/elasticsearch/config
      - ${PWD}/docker/elasticsearch/entrypoint.sh:/usr/local/bin/entrypoint.sh
      - ${ELASTICSEARCH_PERSISTENCE_DIR}/elasticsearch:/usr/share/elasticsearch/data
    user: ${UID:-1000}:${GID:-0}
    command: ["bash", "/usr/local/bin/entrypoint.sh"]
    depends_on:
      - elasticsearch02

  elasticsearch02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    ports:
      - "9201:9200"
      - "9301:9300"
    environment:
      node.name: elasticsearch02
      discovery.seed_hosts: elasticsearch01
      cluster.initial_master_nodes: elasticsearch01, elasticsearch02
      ES_JAVA_OPTS: "-Xms16g -Xmx16g"
    volumes:
      - ${PWD}/docker/elasticsearch:/usr/share/elasticsearch/config
      - ${PWD}/docker/elasticsearch/entrypoint.sh:/usr/local/bin/entrypoint.sh
      - ${ELASTICSEARCH_PERSISTENCE_DIR}/elasticsearch2:/usr/share/elasticsearch/data
    user: ${UID:-1000}:${GID:-0}
    command: ["bash", "/usr/local/bin/entrypoint.sh"]

  proxy-api:
    build: ./docker/proxy-api
    ports:
      - "4001:4001"
    command: npm start
    environment:
      ELASTICSEARCH_HOST: "http://elasticsearch01:9200"
      LOGGER: $PROXY_API_LOGGER
      PORT: $PROXY_API_PORT
    depends_on:
      - elasticsearch01
