version: '3'
services:
  proxy-api:
    build: ./docker/proxy-api
    ports:
      - "4001:4001"
    command: npm start
    environment:
      ELASTICSEARCH_HOST: $ELASTICSEARCH_HOST
      LOGGER: $PROXY_API_LOGGER
      PORT: $PROXY_API_PORT
    depends_on:
      - elasticsearch
