cluster.name: "docker-cluster"
network.host: 0.0.0.0

# minimum_master_nodes need to be explicitly set when bound on a public IP
# set to 1 to allow single node clusters
# Details: https://github.com/elastic/elasticsearch/pull/17288
# discovery.type: single-node
# discovery.zen.minimum_master_nodes: 1


http.cors.enabled: true
http.cors.allow-origin: "*"

http.max_content_length: 2147483647b

xpack.security.enabled: false

# Added 2022/10
#ingest.geoip.downloader.enabled: false

#discovery.zen.ping.unicast.hosts: ["elasticsearch01","elasticsearch02"]
#cluster.initial_master_nodes: ["elasticsearch01","elasticsearch02"]

# Monitoring
#xpack.monitoring.collection.enabled: true
